import io
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_pdf_report(summary_stats, cpk_metrics=None, ml_metrics=None):
    """
    Tạo file PDF báo cáo tổng hợp kết quả phân tích.
    Trả về dữ liệu dạng bytes để Streamlit dùng cho Download Button.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()

    # Định nghĩa phong cách văn bản
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1f77b4'),
        alignment=1,  # Center
        spaceAfter=20
    )

    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#2c3e50'),
        spaceBefore=12,
        spaceAfter=8
    )

    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        spaceAfter=6
    )

    elements = []

    # 1. Tiêu đề Báo cáo
    elements.append(Paragraph("INDUSTRIAL ANALYTICS & QUALITY REPORT", title_style))
    elements.append(Paragraph("Dynamic Summary Report generated by Industrial Platform", body_style))
    elements.append(Spacer(1, 15))

    # 2. Section: Thống kê tổng quan (Summary Statistics)
    if summary_stats is not None and not summary_stats.empty:
        elements.append(Paragraph("1. Data Overview & Summary Statistics", section_style))

        # Format bảng dữ liệu
        table_data = [list(summary_stats.columns)]
        for _, row in summary_stats.iterrows():
            formatted_row = [f"{val:.3f}" if isinstance(val, (int, float)) else str(val) for val in row]
            table_data.append(formatted_row)

        t = Table(table_data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 15))

    # 3. Section: Năng lực quy trình (Cp / CpK Analysis)
    if cpk_metrics:
        elements.append(Paragraph("2. Process Capability (SPC / CpK)", section_style))
        cpk_data = [
            ["Metric Parameter", "Calculated Value"],
            ["Mean (X-bar)", f"{cpk_metrics.get('mean', 0):.3f}"],
            ["Std Deviation (Sigma)", f"{cpk_metrics.get('std', 0):.3f}"],
            ["Process Capability (Cp)", f"{cpk_metrics.get('cp', 0):.3f}"],
            ["Process Capability Index (CpK)", f"{cpk_metrics.get('cpk', 0):.3f}"],
            ["Evaluation Status", str(cpk_metrics.get('status', 'N/A'))]
        ]
        t_cpk = Table(cpk_data, colWidths=[200, 250])
        t_cpk.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#16a085')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f4f6f7')),
        ]))
        elements.append(t_cpk)
        elements.append(Spacer(1, 15))

    # 4. Section: Mô hình Hồi quy (Machine Learning Summary)
    if ml_metrics:
        elements.append(Paragraph("3. Linear Regression Model Summary", section_style))
        ml_data = [
            ["Model Parameter", "Value"],
            ["R-Squared Score (R2)", f"{ml_metrics.get('r2', 0):.3f}"],
            ["Root Mean Squared Error (RMSE)", f"{ml_metrics.get('rmse', 0):.3f}"],
            ["Training Sample Size", str(ml_metrics.get('n_samples', 0))],
            ["Intercept", f"{ml_metrics.get('intercept', 0):.4f}"]
        ]
        t_ml = Table(ml_data, colWidths=[200, 250])
        t_ml.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2980b9')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f4f6f7')),
        ]))
        elements.append(t_ml)

    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()